### ISSUE TITLE
Eror CORs

### ISSUE THREAD

**Issue by ariefdluffy** [Abdurozzaq/Oashier#4]
Access to XMLHttpRequest at 'http://localhost:8000/api/auth/login' from origin 'http://127.0.0.1:8000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: The value of the 'Access-Control-Allow-Credentials' header in the response is '' which must be 'true' when the request's credentials mode is 'include'. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute.

ga bisa login kenapa ya ?

**Comment by Abdurozzaq** [comment]
Halo, ariefdluffy.
Maaf atas lama nya respon Saya. Untuk permasalahan Anda, bisa lebih detail? Anda menggunakan Server Local Atau Hosting? 

Cara yang bisa Anda coba : 
1. Buka file resources/js/app.js.
2. Ubah "axios.defaults.baseURL" dengan url / domain Anda.
